name: myenv
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - argon2-cffi=25.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=25.1.0=py312h02ab6af_0
  - arrow=1.3.0=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - async-lru=2.0.5=pyh29332c3_0
  - babel=2.17.0=pyhd8ed1ab_0
  - bleach=6.2.0=pyh29332c3_4
  - bleach-with-css=6.2.0=h82add2a_4
  - brotli-python=1.0.9=py312h5da7b33_9
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.10.5=h4c7d964_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - debugpy=1.8.16=py312h885b0b7_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.6.4=h8ddb27b_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=7.0.1=pyh6dadd2b_0
  - ipython=9.6.0=pyh6be1c34_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - json5=0.12.1=pyhd8ed1ab_0
  - jsonpointer=2.0=py_0
  - jsonschema-with-format-nongpl=4.25.1=he01879c_0
  - jupyter-lsp=2.3.0=pyhcf101f3_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=py312haa95532_0
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_server=2.17.0=pyhcf101f3_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.4.9=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.27.3=pyhd8ed1ab_1
  - krb5=1.21.3=hdf4eb48_0
  - lark=1.3.0=pyhd8ed1ab_0
  - libffi=3.4.4=hd77b12b_1
  - libsodium=1.0.20=hc70643c_0
  - lz4-c=1.9.4=hcfcfb64_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mistune=3.1.4=pyhcf101f3_0
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert-core=7.16.6=pyh29332c3_0
  - nbformat=5.10.4=pyhd8ed1ab_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - notebook=7.4.7=pyhd8ed1ab_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - openssl=3.5.4=h725018a_0
  - overrides=7.7.0=pyhd8ed1ab_1
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.5=pyhcf101f3_0
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=24.2=py312haa95532_0
  - platformdirs=4.5.0=pyhcf101f3_0
  - prometheus_client=0.23.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.0.0=py312h02ab6af_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pycparser=2.22=pyh29332c3_1
  - pysocks=1.7.1=pyh09c184e_7
  - python=3.12.7=h14ffc60_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - pywin32=311=py312h885b0b7_0
  - pywinpty=2.0.15=py312h72d21ff_0
  - pyzmq=27.1.0=py312h7149c55_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rfc3987-syntax=1.1.0=pyhe01879c_1
  - rpds-py=0.22.3=py312h636fa0f_0
  - send2trash=1.8.3=pyh5737063_1
  - setuptools=75.1.0=py312haa95532_0
  - six=1.17.0=pyhe01879c_1
  - sniffio=1.3.1=pyhd8ed1ab_1
  - sqlite=3.45.3=h2bbff1b_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - terminado=0.18.1=pyh5737063_0
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.14=h0416ee5_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - types-python-dateutil=2.9.0.20251008=pyhd8ed1ab_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - ucrt=10.0.26100.0=h57928b3_0
  - uri-template=1.3.0=pyhd8ed1ab_1
  - vc=14.40=haa95532_2
  - vc14_runtime=14.44.35208=h818238b_32
  - vcomp14=14.44.35208=h818238b_32
  - vs2015_runtime=14.44.35208=h38c0c73_32
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - webcolors=24.11.1=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - wheel=0.44.0=py312haa95532_0
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - winpty=0.4.3=4
  - xz=5.4.6=h8cc25b3_1
  - yaml=0.2.5=h6a83c73_3
  - zeromq=4.3.5=h5bddc39_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.2.13=h8cc25b3_1
  - zstandard=0.23.0=py312h4fc1ca9_1
  - zstd=1.5.6=h8880b57_0
  - pip:
      - altair==5.5.0
      - annotated-types==0.7.0
      - anyio==4.8.0
      - attrs==24.3.0
      - beautifulsoup4==4.12.3
      - blinker==1.9.0
      - cachetools==5.5.0
      - certifi==2024.12.14
      - cffi==1.17.1
      - chardet==5.2.0
      - charset-normalizer==3.4.1
      - click==8.1.8
      - cssselect==1.2.0
      - distro==1.9.0
      - docstring-parser==0.16
      - et-xmlfile==2.0.0
      - filelock==3.17.0
      - fsspec==2024.12.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - google-ai-generativelanguage==0.6.15
      - google-api-core==2.24.1
      - google-api-python-client==2.160.0
      - google-auth==2.38.0
      - google-auth-httplib2==0.2.0
      - google-generativeai==0.8.4
      - googleapis-common-protos==1.66.0
      - groq==0.16.0
      - grpcio==1.70.0
      - grpcio-status==1.70.0
      - h11==0.14.0
      - html2text==2024.2.26
      - httpcore==1.0.7
      - httplib2==0.22.0
      - huggingface-hub==0.28.0
      - idna==3.10
      - jinja2==3.1.5
      - jiter==0.11.1
      - jsonpatch==1.33
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - langchain==1.0.0
      - langchain-core==1.0.0
      - langchain-openai==1.0.0
      - langgraph==1.0.0
      - langgraph-checkpoint==2.1.2
      - langgraph-prebuilt==1.0.0
      - langgraph-sdk==0.2.9
      - langsmith==0.4.37
      - lxml==5.3.0
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - mdurl==0.1.2
      - narwhals==1.21.1
      - numpy==2.2.1
      - openai==2.5.0
      - openpyxl==3.1.5
      - orjson==3.11.3
      - ormsgpack==1.11.0
      - outcome==1.3.0.post0
      - packaging==24.2
      - pandas==2.2.3
      - phidata==2.7.10
      - pillow==11.1.0
      - polars==1.34.0
      - polars-runtime-32==1.34.0
      - proto-plus==1.26.0
      - protobuf==5.29.3
      - pyarrow==18.1.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pydantic==2.10.5
      - pydantic-core==2.27.2
      - pydantic-settings==2.7.1
      - pydeck==0.9.1
      - pygments==2.19.1
      - pyparsing==3.2.1
      - python-dotenv==1.0.1
      - pytz==2024.2
      - pyyaml==6.0.2
      - readability-lxml==0.8.1
      - referencing==0.35.1
      - regex==2024.11.6
      - requests==2.32.3
      - requests-toolbelt==1.0.0
      - rich==13.9.4
      - rsa==4.9
      - safetensors==0.5.2
      - selenium==4.27.1
      - shellingham==1.5.4
      - smmap==5.0.2
      - sortedcontainers==2.4.0
      - soupsieve==2.6
      - streamlit==1.41.1
      - streamlit-tags==1.2.8
      - tenacity==9.0.0
      - tiktoken==0.8.0
      - tokenizers==0.21.0
      - toml==0.10.2
      - tomli==2.2.1
      - tornado==6.4.2
      - tqdm==4.67.1
      - transformers==4.48.1
      - trio==0.28.0
      - trio-websocket==0.11.1
      - typer==0.15.1
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - uritemplate==4.1.1
      - urllib3==2.3.0
      - watchdog==6.0.0
      - webdriver-manager==4.0.2
      - websocket-client==1.8.0
      - wsproto==1.2.0
      - xxhash==3.6.0

