version: "3.8"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: hr
      POSTGRES_PASSWORD: hrpass
      POSTGRES_DB: hrdb
    ports: ["5432:5432"]
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports: ["5050:80"]
